pull_request_rules:
### Auto merge ###################
  - name: auto merge passing Dependabot pull requests
    conditions:
      - author~=dependabot(-preview)?\[bot\]
      - label~=dependencies
    actions:
      merge:
        method: squash
        strict: smart
