  
language: node_js
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: test
      script:
        # Run tests
        - npm run test:unit
    - stage: build
      script:
        # Build all
        - npm run build
